language: r
sudo: false
cache: packages

env:
  matrix:
    - CXX_OLEVEL=2 CXX=clang++

before_install:
  - mkdir -p ~/.R/
  - echo "CXX14 = `R CMD config CXX14`" >> ~/.R/Makevars
  - echo "CXX14FLAGS = `R CMD config CXX14FLAGS` -pedantic -g0"
  - export CLANG_EXTRA_ARG=""
  - if [[ $CXX = "clang++" ]] ;  then export CLANG_EXTRA_ARG=" -Qunused-arguments -fcolor-diagnostics " ; fi
  - sed -i.bak "s/ g++/ ${CXX}${CLANG_EXTRA_ARG}/" ~/.R/Makevars
  - sed -i.bak "s/O[0-3]/O$CXX_OLEVEL/" ~/.R/Makevars

notifications:
  email: false

r_github_packages:
  - jimhester/covr

after_success:
  - Rscript -e 'covr::codecov()'
